icp_nav_follow:
  ros__parameters:
    x_pid:
      antiwindup: True
      p: 2.0
      i: 0.5
      d: 0.0
      i_clamp_max:  0.05
      i_clamp_min: -0.05
    y_pid:
      antiwindup: True
      p: 2.0
      i: 0.5
      d: 0.0
      i_clamp_max:  0.05
      i_clamp_min: -0.05
    w_pid:
      antiwindup: True
      p: 2.0
      i: 0.5
      d: 0.0
      i_clamp_max:  0.05
      i_clamp_min: -0.05
    x_pid_icp:
      antiwindup: True
      p: 0.5
      i: 0.2
      d: 0.0
      i_clamp_max:  0.05
      i_clamp_min: -0.05
    y_pid_icp:
      antiwindup: True
      p: 0.5
      i: 0.2
      d: 0.0
      i_clamp_max:  0.05
      i_clamp_min: -0.05
    w_pid_icp:
      antiwindup: True
      p: 0.5
      i: 0.2
      d: 0.0
      i_clamp_max:  0.05
      i_clamp_min: -0.05
